[package]
name = "problem-002"
version = "0.1.0"
authors = ["kenkyu392 <57144941+kenkyu392@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
