// Problem 2: Even Fibonacci numbers
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms
// will be:
//   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.
fn main() {
    let want = 4613732;
    let mut got = 0;
    let (mut prev, mut next) = (0, 1);
    while next < 4000000 {
        if next % 2 == 0 {
            got += next;
        }
        let tmp = prev;
        prev = next;
        next = prev + tmp;
    }
    println!("want:{} == got:{} = {}", want, got, want == got)
}
